### PR TITLE
Rebuild for r-base 4.4 and UCRT mingw toolchain

### PR DESCRIPTION
**Pull request by danielnachun**

### CODE REVIEW

**Comment by danielnachun** [comment]
@conda-forge-admin please restart ci

**Comment by danielnachun** [comment]
Travis was being very flaky here so I just switched to emulated Azure.  This package doesn't take that long to build on there so I think this is a better option for now.

**Comment by mfansler** [comment]
@conda-forge-admin please rerender

**Comment by mfansler** [comment]
@conda-forge-admin please rerender

**Comment by mfansler** [comment]
I'm rather at a loss what is broken here. 🫤 🤷  Don't recall seeing this Appveyor check before, and all the build jobs short-circuit.

**Comment by danielnachun** [comment]
The only solution I've found for this right now is to make an empty commit.  I'll do that now.

**Comment by danielnachun** [comment]
Shoot, can you repush your commits now, I accidentally force pushed over them.  Sorry!

**Comment by mfansler** [comment]
No worries!

**Comment by mfansler** [comment]
@conda-forge-admin please rerender

**Comment by danielnachun** [comment]
We're all set here now, thanks for pushing the commits!

**Review by mfansler — APPROVED** [review]

**Pull request merged**
